### PR TITLE
Fix #5 and #6

### LINKED ISSUE #5: Setup prettier, eslint, husky
It'll be nice to setup [prettier](https://prettier.io/) & [eslint](https://eslint.org/) to avoid formatting and linting issues. 
You can add the same in your `test` script to ensure it breaks on such issues.

Lastly, you may add [husky](https://www.npmjs.com/package/husky) to add a `prepush` script that runs the test on the contributors machine before pushing. This would block broken code as early as possible. 

Let me know if you need help with the same.

### PR DESCRIPTION
**Pull request by Akshitaag**
Add husky and prepush
Log comments when matching a particular string and label

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,10 +1,22 @@
...
+    // GitHub API calls. This will return:
+    //   {owner: 'yourname', repo: 'yourrepo', number: 123, body: 'Hello World!}
+
+    const comparisonString = 'Can I work on this?'
+    const label = 'first-timers-only'
+    let check = false
+    const labelArray = context.payload.issue.labels
 
+    if (context.payload.comment.body === comparisonString) {
+      labelArray.forEach(function (elem) {
```
Comment (bogas04) [inline index.js]: We can make use of [`Array.prototype.includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

This would eliminate the requirement of `check` variable and tidy up the code.

File: index.js [hunk 2]
```diff
@@ -1,10 +1,22 @@
...
+    // `context` extracts information from the event, which can be passed to
+    // GitHub API calls. This will return:
+    //   {owner: 'yourname', repo: 'yourrepo', number: 123, body: 'Hello World!}
+
+    const comparisonString = 'Can I work on this?'
+    const label = 'first-timers-only'
+    let check = false
+    const labelArray = context.payload.issue.labels
 
+    if (context.payload.comment.body === comparisonString) {
```
Comment (bogas04) [inline index.js]: I feel it'll be nice to abstract this out as a function.

`isClaimingIssue(comment.body)`

This way the logic of figuring that out can be separated out and updated without changing this piece of code.
